#import "../fragments/media-card.graphql"

fragment AiringMediaFields on Media {
  ...MediaCardFields
  bannerImage
  externalLinks {
    id
    site
    url
    type
  }
}

query AiringSchedules($airingAt_greater: Int, $airingAt_lesser: Int, $page: Int) {
  Page(page: $page, perPage: 50) {
    pageInfo {
      currentPage
      lastPage
      hasNextPage
    }
    airingSchedules(
      airingAt_greater: $airingAt_greater
      airingAt_lesser: $airingAt_lesser
      sort: TIME
    ) {
      id
      airingAt
      episode
      timeUntilAiring
      media {
        ...AiringMediaFields
      }
    }
  }
}
