#import "../fragments/media-card-browse.graphql"
#import "../fragments/character-card-browse.graphql"
#import "../fragments/staff-card-browse.graphql"

query GlobalSearch($search: String) {
  anime: Page(perPage: 5) {
    media(type: ANIME, search: $search) {
      ...MediaCardBrowseFields
    }
  }
  manga: Page(perPage: 5) {
    media(type: MANGA, search: $search) {
      ...MediaCardBrowseFields
    }
  }
  characters: Page(perPage: 5) {
    characters(search: $search) {
      ...CharacterCardBrowseFields
    }
  }
  staff: Page(perPage: 5) {
    staff(search: $search) {
      ...StaffCardBrowseFields
    }
  }
}
