#import "../fragments/media-card.graphql"

query HomeSections(
  $perPage: Int!
  $currentSeason: MediaSeason!
  $currentSeasonYear: Int!
  $nextSeason: MediaSeason!
  $nextSeasonYear: Int!
) {
  trending: Page(page: 1, perPage: $perPage) {
    media(type: ANIME, sort: [TRENDING_DESC]) {
      ...MediaCardFields
    }
  }
  airingNow: Page(page: 1, perPage: $perPage) {
    media(type: ANIME, sort: [POPULARITY_DESC], status: RELEASING) {
      ...MediaCardFields
    }
  }
  popularThisSeason: Page(page: 1, perPage: $perPage) {
    media(
      type: ANIME
      sort: [POPULARITY_DESC]
      season: $currentSeason
      seasonYear: $currentSeasonYear
    ) {
      ...MediaCardFields
    }
  }
  upcomingNextSeason: Page(page: 1, perPage: $perPage) {
    media(
      type: ANIME
      sort: [POPULARITY_DESC]
      season: $nextSeason
      seasonYear: $nextSeasonYear
      status_in: [NOT_YET_RELEASED]
    ) {
      ...MediaCardFields
    }
  }
  allTimePopular: Page(page: 1, perPage: $perPage) {
    media(type: ANIME, sort: [POPULARITY_DESC]) {
      ...MediaCardFields
    }
  }
  top100: Page(page: 1, perPage: $perPage) {
    media(type: ANIME, sort: [SCORE_DESC]) {
      ...MediaCardFields
    }
  }
}
