#import "../fragments/media-card-grid.graphql"
#import "../fragments/page-info.graphql"

query MediaPage(
  $page: Int
  $perPage: Int
  $sort: [MediaSort]
  $season: MediaSeason
  $seasonYear: Int
  $status: MediaStatus
  $status_in: [MediaStatus]
  $search: String
  $genre_in: [String]
  $format_in: [MediaFormat]
  $tag_in: [String]
  $averageScore_greater: Int
  $episodes_greater: Int
  $episodes_lesser: Int
  $duration_greater: Int
  $duration_lesser: Int
  $startDate_greater: FuzzyDateInt
  $startDate_lesser: FuzzyDateInt
  $countryOfOrigin: CountryCode
  $source_in: [MediaSource]
) {
  Page(page: $page, perPage: $perPage) {
    pageInfo {
      ...PageInfoFields
    }
    media(
      type: ANIME
      sort: $sort
      season: $season
      seasonYear: $seasonYear
      status: $status
      status_in: $status_in
      search: $search
      genre_in: $genre_in
      format_in: $format_in
      tag_in: $tag_in
      averageScore_greater: $averageScore_greater
      episodes_greater: $episodes_greater
      episodes_lesser: $episodes_lesser
      duration_greater: $duration_greater
      duration_lesser: $duration_lesser
      startDate_greater: $startDate_greater
      startDate_lesser: $startDate_lesser
      countryOfOrigin: $countryOfOrigin
      source_in: $source_in
    ) {
      ...MediaCardGridFields
    }
  }
}
